* Зависимости

- Нестандартный [[http://github.com/Menschenkindlein/esrap][esrap]]
- cl-fad
- "Кодогенератор" [[http://github.com/Menschenkindlein/ucg][ucg]]

* Работа

** Бинарник

Работать нужно с бинарником движка.  Toplevel - =#'init=.

** Рабочая директория

При запуске бинарник пробует использовать текущую директорию для
конфигурации сайта и загрузки существующих баз данных.

Пример содержимого рабочей директории сайта можно посмотреть в
[[http://github.com/Menschenkindlein/test-list-site][test-list-site]].

Желательно иметь в рабочей директории папки objects и printers с
конфигурацией объектов и принтеров, которые используются на сайте.

Конфигурация пишется на обычном лиспе. =*package*= --- =:list-site=.

** Ход работы

REPL движка поддерживает следующие функции:

=(excrect <тип объекта> <имя объекта>)= --- Преобразует объект в удобную
  для редактирования форму, возвращает путь к созданному файлу. Если
  объекта с таким названием не существует - создает пример объекта.

=(consume)= --- Поглощает все доступные объекты.

=(build <принтер> <тип объекта> <имя объекта>)= --- Печатает объект в
  конечной форме с использованием заявленного принтера. В зависимости
  от конфигурации принтера, печатает рекурсивно объекты, на которые
  имеются ссылки.

=(exit)= --- Выход.
